const mutations = {
  IS_LOGGED_IN: "IS_LOGGED_IN",
  LOGIN_LOADER: "LOGIN_LOADER",
  SHOW_NOTIFY: "SHOW_NOTIFY",
  USER: "USER",
  IS_SING_UP: "IS_SING_UP",
  RESERT_PASSWORD: "RESERT_PASSWORD",
};

export default mutations;
